cask_args appdir: "/Applications"

tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"

brew "awscli"
brew "ctags"
brew "direnv"
brew "envchain"
brew "fzf"
brew "gh"
brew "gnupg"
brew "heroku"
brew "htop"
brew "mas"
brew "msmtp"
brew "mtr"
brew "mutt"
brew "nmap"
brew "offlineimap"
brew "p7zip"
brew "pinentry-mac"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "shellcheck"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "unrar"
brew "vim", args: ["with-override-system-vi"]

cask "1password"
cask "bartender"
cask "docker"
cask "firefox"
cask "flux"
cask "font-source-code-pro"
cask "google-chrome"
cask "omnifocus"
cask "signal"
cask "sizeup"
cask "slack"
cask "zoomus"

mas "Monosnap", id: 540348655
