cask_args appdir: "/Applications"

tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"

brew "awscli"
brew "direnv"
brew "envchain"
brew "fzf"
brew "gh"
brew "gnupg"
brew "heroku"
brew "htop"
brew "jq"
brew "mas"
brew "msmtp"
brew "mtr"
brew "mutt"
brew "neovim"
brew "nmap"
brew "node"
brew "offlineimap"
brew "p7zip"
brew "pinentry-mac"
brew "pv"
brew "rbenv"
brew "ripgrep"
brew "ruby-build"
brew "shellcheck"
brew "sqlfmt"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "universal-ctags"
brew "urlview"
brew "w3m"
brew "watch"

cask "1password"
cask "1password-cli"
cask "bartender"
cask "blockblock"
cask "font-sauce-code-pro-nerd-font"
cask "font-source-code-pro"
cask "ghostty"
cask "google-chrome"
cask "knockknock"
cask "lulu"
cask "notunes"
cask "omnifocus"
cask "ransomwhere"
cask "reikey"
cask "sizeup"
cask "slack"

mas "Monosnap", id: 540348655
